create table "fixed-deposit"
(
    id               uuid not null primary key ,
    close_date       date,
    current_amount   numeric(38, 2),
    institution_name varchar(255),
    interest_rate    numeric(38, 2),
    maturity_amount  numeric(38, 2),
    nominee_name     varchar(255),
    open_date        date,
    principal_amount numeric(38, 2),
    user_id          varchar(255),
    tax_percent      numeric(3,2)
);

ALTER TABLE "fixed-deposit" alter column id set default gen_random_uuid();

create table "fixed-deposit-statement"
(
    amount           numeric(38, 2),
    expense          smallint
        constraint "fixed-deposit-statement_expense_check"
            check ((expense >= 0) AND (expense <= 1)),
    tax_amount       numeric(38, 2),
    transaction_date date,
    update_date      date,
    id               bigint generated by default as identity
        primary key,
    fixed_deposit_id uuid
);